### ISSUE TITLE
Argument must be non-negative (Error process has died)

### ISSUE THREAD

**Issue by cmakelabs** [minwoo0611/MA-LIO#30]
Trying to run on my own rosbag, I got this error
```
malio_mapping: /home/noetic/maLIO_ws/src/MA-LIO/MA_LIO/include/IKFoM_toolkit/esekfom/../mtk/types/../src/mtkmath.hpp:151: std::pair<_FIter, _FIter> MTK::cos_sinc_sqrt(const scalar&) [with scalar = double]: Assertion `x2>=0 && "argument must be non-negative and must not be nan/-nan"' failed.
[laserMapping-2] process has died [pid 538969, exit code -6, cmd /home/noetic/maLIO_ws/devel/lib/ma_lio/malio_mapping __name:=laserMapping __log:=/home/noetic/.ros/log/c4c48244-2cd3-11ef-a22b-6b3260c4d878/laserMapping-2.log].
log file: /home/noetic/.ros/log/c4c48244-2cd3-11ef-a22b-6b3260c4d878/laserMapping-2*.log
```
I have tried the same rosbag, with single LIDAR and it worked without any issues on FAST-LIO.
I note that I have found a similar issue in a different package on the internet (FASTER-LIO), at this [link](https://coder.social/gaoxiang12/faster-lio/issues/10), which was later fixed by the authors.

**Comment by Akina2001** [comment]
Hello, I would like to ask if you have solved this problem?

**Comment by minwoo0611** [comment]
Hello, @cmakelabs,

Similar to [issue 31](https://github.com/minwoo0611/MA-LIO/issues/31), there was an error introduced in our recent pull request update.

While I cannot confirm that your error source is the same as the one in the previous issue (since your issue involves your own rosbag file and the previous one involved our city dataset), I believe the source of the problem may be similar.

The issue stems from the most recent pull request, which introduced changes related to uncertainty in plane estimation.

In the updated code, all points now have identical uncertainty values, meaning that the maximum and minimum uncertainties in the measurements are the same. Our implementation uses fixed interval conversion (FIC) to ensure measurements fall within a user-defined interval. During this process, the difference between the maximum and minimum uncertainties is calculated and used in the denominator term, as referenced in equation (13) of the MA-LIO journal.

However, since the maximum and minimum uncertainties are now the same, the denominator becomes zero, causing the error.

I have added new conditions to handle cases where the maximum and minimum uncertainties are identical. You can see the changes [here](https://github.com/minwoo0611/MA-LIO/blob/5dbb867b1770cec90b2d3d395313df890edbda7d/MA_LIO/src/laserMapping.cpp#L651-L656).

Thank you for identifying this issue!

If you have any additional issues, feel free to contact me.

**Comment by gcouncil-cmu** [comment]
Hello, 

I'm encountering the same issue, and I'm using the updated code. I managed to get the urban data set to work, but when I play back my own rosbag (which is extremely similar to the urban data set), I encounter this error after a few frames. The handful of frames that are populated before it crashes are basically junk -- the lidars seem very misaligned even with extrinsic calibration on. Any ideas?

**Comment by minwoo0611** [comment]
Hello @gcouncil-cmu,

Thank you for using our MA-LIO package. To help debug your issue, I have a few questions:

1. Are you referring to a public dataset (like urbanNav, complex urban dataset, or city dataset) or your own private acquisition dataset when you mention the urban dataset?
2. Is it possible for me to access the dataset for debugging purposes?
3. If the initial frames are misaligned, please verify that the extrinsic parameters are correct. If the map initialization fails, the number of matching features will be zero, which can cause the error you mentioned.
4. If the extrinsic parameters are accurate, try setting `extrinsic_est_en=False` in the configuration.

I hope these suggestions help resolve your issue. Looking forward to your response.

Thank you,
Minwoo
