### ISSUE TITLE
Operation Problem

### ISSUE THREAD

**Issue by Akina2001** [minwoo0611/MA-LIO#31]
I would like to ask why it cannot run according to the default city.xml.
![1719479180078](https://github.com/minwoo0611/MA-LIO/assets/101882396/06e3f329-41f0-4381-9dbc-30b044b66913)

**Comment by minwoo0611** [comment]
Hello, @Akina2001,

The issue stems from the most recent pull request, which introduced changes related to uncertainty in plane estimation.

In the updated code, all points now have identical uncertainty values, meaning that the maximum and minimum uncertainties in the measurements are the same. Our implementation uses fixed interval conversion (FIC) to ensure measurements fall within a user-defined interval. During this process, the difference between the maximum and minimum uncertainties is calculated and used in the denominator term, as referenced in equation (13) of the MA-LIO journal.

However, since the maximum and minimum uncertainties are now the same, the denominator becomes zero, causing the error.

I have added new conditions to handle cases where the maximum and minimum uncertainties are identical. You can see the changes [here](https://github.com/minwoo0611/MA-LIO/blob/5dbb867b1770cec90b2d3d395313df890edbda7d/MA_LIO/src/laserMapping.cpp#L651-L656).

Thank you for identifying this issue!

If you have any further questions, please feel free to open additional issues. I am currently quite busy, so I may not be able to respond immediately, but I will make sure to address your concerns as soon as possible.

**Comment by Akina2001** [comment]
Hello,
I appreciate your quick response. I successfully run CityDataset and UrbanNav's multi-lidar in the latest version of the code, but I found a problem. The single-lidar configured according to README and Issue does not run properly for UrbanLoco_HK, Utbm and 2019-04-28-20-58-02.bag in UrbanNav with the same problem:
![1](https://github.com/minwoo0611/MA-LIO/assets/101882396/4fb318f8-b3ab-4cad-b54f-0c59995aa787)
![2](https://github.com/minwoo0611/MA-LIO/assets/101882396/4c864454-1739-4e29-a28f-72a23188a9a3)
![3](https://github.com/minwoo0611/MA-LIO/assets/101882396/b7c4f4ca-9db5-4728-a1a3-2e6b3c06e109)
![4](https://github.com/minwoo0611/MA-LIO/assets/101882396/26379f37-b768-4278-b136-5ccc4aec20c0)
![5](https://github.com/minwoo0611/MA-LIO/assets/101882396/16ab7a56-d59c-4d5b-b044-b2df4dde82d8)

**Comment by Akina2001** [comment]
Hello, 
I found the key to the problem. I think MA-LIO's velodyne_handler lacks the necessary timestamp calculation step. Adding the following code can run UrbanLoco and other codes normally (copy from fastlio):
![1719714636809](https://github.com/minwoo0611/MA-LIO/assets/101882396/01f1bcbe-1e28-4964-8994-0238216d5441)

**Comment by Akina2001** [comment]
I would like to apologize for my previous incorrect solution approach. After conducting further experiments and gaining a deeper understanding, I have realized that merely following the modification "modified by fastlio2 for urbanloco utbm or no lidar times dataset" will lead to other conflicts.
